### ISSUE TITLE
ArrayList

### ISSUE THREAD

**Issue by jrgs** [cafetolo72/DataAccessJOB2122#3]
https://github.com/cafetolo72/DataAccessJOB2122/blob/4e1ea5a6807d398dd2fb25fcbf274308c52f086e/Unit2/Exercise4.4.4/src/com/JOB2122/Main.java#L30

Idem de nuevo, ¿para qué lo metes en un ArrayList? Imprímelo y ya está. Por cierto, hay que mostrar también el número de línea donde estaba.

**Comment by cafetolo72** [comment]
@jrgs 
Problema solucionado, quitado ArrayList y añadido contador de líneas.
